Adding entity_key param and 'user_var_table' as input, since its requ…
rudderlabs/rudderstack-profiles-shopify-churn pull request #25
Opened 2024-01-11 09:29 UTC by cnu1439

…ired to get model_hash from pb compile

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-01-11 13:05 UTC, dpatchigolla requested changes

2024-01-11 13:05 UTC, dpatchigolla commented on models/profiles.yaml
> +            entiry_key: *entity_name # Name of entity key
Typo - it should be `entity_key`; Can you run it once? It should ideally have thrown an error.

2024-01-11 15:42 UTC, cnu1439 commented on models/profiles.yaml
> +            entiry_key: *entity_name # Name of entity key
yep, it threw the error. corrected. running it again.

2024-01-12 13:16 UTC, dpatchigolla approved these changes

2024-01-12 13:17 UTC, merged